/**
 * Places365 365 类 → 9 app 分类映射。
 * 由 scripts/places365_to_app.py 自动生成（按关键词归类）。
 * 共 365 类，分布：{'travel_scenery': 142, 'social_activities': 95, 'other': 94, 'foods': 25, 'single_person': 8, 'pets': 1}。
 *
 * 数据源：CSAILVision/places365 standard categories file.
 */

// 数组下标 = Places365 类 id（模型输出 argmax 值）
// 每项 { name, category } —— name 用于诊断，category 是 9 app 类
export const PLACES365_CLASSES = [
  { name: "airfield", category: "travel_scenery" },  // 0
  { name: "airplane_cabin", category: "travel_scenery" },  // 1
  { name: "airport_terminal", category: "travel_scenery" },  // 2
  { name: "alcove", category: "other" },  // 3
  { name: "alley", category: "travel_scenery" },  // 4
  { name: "amphitheater", category: "social_activities" },  // 5
  { name: "amusement_arcade", category: "social_activities" },  // 6
  { name: "amusement_park", category: "social_activities" },  // 7
  { name: "apartment_building/outdoor", category: "travel_scenery" },  // 8
  { name: "aquarium", category: "other" },  // 9
  { name: "aqueduct", category: "travel_scenery" },  // 10
  { name: "arcade", category: "social_activities" },  // 11
  { name: "arch", category: "travel_scenery" },  // 12
  { name: "archaelogical_excavation", category: "travel_scenery" },  // 13
  { name: "archive", category: "travel_scenery" },  // 14
  { name: "arena/hockey", category: "social_activities" },  // 15
  { name: "arena/performance", category: "social_activities" },  // 16
  { name: "arena/rodeo", category: "social_activities" },  // 17
  { name: "army_base", category: "other" },  // 18
  { name: "art_gallery", category: "other" },  // 19
  { name: "art_school", category: "social_activities" },  // 20
  { name: "art_studio", category: "social_activities" },  // 21
  { name: "artists_loft", category: "other" },  // 22
  { name: "assembly_line", category: "other" },  // 23
  { name: "athletic_field/outdoor", category: "travel_scenery" },  // 24
  { name: "atrium/public", category: "foods" },  // 25
  { name: "attic", category: "other" },  // 26
  { name: "auditorium", category: "social_activities" },  // 27
  { name: "auto_factory", category: "other" },  // 28
  { name: "auto_showroom", category: "other" },  // 29
  { name: "badlands", category: "travel_scenery" },  // 30
  { name: "bakery/shop", category: "foods" },  // 31
  { name: "balcony/exterior", category: "other" },  // 32
  { name: "balcony/interior", category: "other" },  // 33
  { name: "ball_pit", category: "other" },  // 34
  { name: "ballroom", category: "social_activities" },  // 35
  { name: "bamboo_forest", category: "travel_scenery" },  // 36
  { name: "bank_vault", category: "other" },  // 37
  { name: "banquet_hall", category: "social_activities" },  // 38
  { name: "bar", category: "foods" },  // 39
  { name: "barn", category: "foods" },  // 40
  { name: "barndoor", category: "foods" },  // 41
  { name: "baseball_field", category: "travel_scenery" },  // 42
  { name: "basement", category: "other" },  // 43
  { name: "basketball_court/indoor", category: "social_activities" },  // 44
  { name: "bathroom", category: "single_person" },  // 45
  { name: "bazaar/indoor", category: "social_activities" },  // 46
  { name: "bazaar/outdoor", category: "social_activities" },  // 47
  { name: "beach", category: "social_activities" },  // 48
  { name: "beach_house", category: "social_activities" },  // 49
  { name: "beauty_salon", category: "other" },  // 50
  { name: "bedchamber", category: "single_person" },  // 51
  { name: "bedroom", category: "single_person" },  // 52
  { name: "beer_garden", category: "foods" },  // 53
  { name: "beer_hall", category: "other" },  // 54
  { name: "berth", category: "other" },  // 55
  { name: "biology_laboratory", category: "other" },  // 56
  { name: "boardwalk", category: "other" },  // 57
  { name: "boat_deck", category: "other" },  // 58
  { name: "boathouse", category: "travel_scenery" },  // 59
  { name: "bookstore", category: "other" },  // 60
  { name: "booth/indoor", category: "other" },  // 61
  { name: "botanical_garden", category: "travel_scenery" },  // 62
  { name: "bow_window/indoor", category: "other" },  // 63
  { name: "bowling_alley", category: "social_activities" },  // 64
  { name: "boxing_ring", category: "other" },  // 65
  { name: "bridge", category: "travel_scenery" },  // 66
  { name: "building_facade", category: "travel_scenery" },  // 67
  { name: "bullring", category: "other" },  // 68
  { name: "burial_chamber", category: "other" },  // 69
  { name: "bus_interior", category: "other" },  // 70
  { name: "bus_station/indoor", category: "social_activities" },  // 71
  { name: "butchers_shop", category: "foods" },  // 72
  { name: "butte", category: "other" },  // 73
  { name: "cabin/outdoor", category: "other" },  // 74
  { name: "cafeteria", category: "foods" },  // 75
  { name: "campsite", category: "travel_scenery" },  // 76
  { name: "campus", category: "travel_scenery" },  // 77
  { name: "canal/natural", category: "travel_scenery" },  // 78
  { name: "canal/urban", category: "travel_scenery" },  // 79
  { name: "candy_store", category: "other" },  // 80
  { name: "canyon", category: "travel_scenery" },  // 81
  { name: "car_interior", category: "other" },  // 82
  { name: "carrousel", category: "other" },  // 83
  { name: "castle", category: "travel_scenery" },  // 84
  { name: "catacomb", category: "other" },  // 85
  { name: "cemetery", category: "travel_scenery" },  // 86
  { name: "chalet", category: "travel_scenery" },  // 87
  { name: "chemistry_lab", category: "other" },  // 88
  { name: "childs_room", category: "other" },  // 89
  { name: "church/indoor", category: "social_activities" },  // 90
  { name: "church/outdoor", category: "social_activities" },  // 91
  { name: "classroom", category: "social_activities" },  // 92
  { name: "clean_room", category: "other" },  // 93
  { name: "cliff", category: "travel_scenery" },  // 94
  { name: "closet", category: "single_person" },  // 95
  { name: "clothing_store", category: "other" },  // 96
  { name: "coast", category: "travel_scenery" },  // 97
  { name: "cockpit", category: "other" },  // 98
  { name: "coffee_shop", category: "foods" },  // 99
  { name: "computer_room", category: "other" },  // 100
  { name: "conference_center", category: "social_activities" },  // 101
  { name: "conference_room", category: "social_activities" },  // 102
  { name: "construction_site", category: "other" },  // 103
  { name: "corn_field", category: "travel_scenery" },  // 104
  { name: "corral", category: "other" },  // 105
  { name: "corridor", category: "other" },  // 106
  { name: "cottage", category: "travel_scenery" },  // 107
  { name: "courthouse", category: "social_activities" },  // 108
  { name: "courtyard", category: "social_activities" },  // 109
  { name: "creek", category: "travel_scenery" },  // 110
  { name: "crevasse", category: "travel_scenery" },  // 111
  { name: "crosswalk", category: "other" },  // 112
  { name: "dam", category: "travel_scenery" },  // 113
  { name: "delicatessen", category: "foods" },  // 114
  { name: "department_store", category: "other" },  // 115
  { name: "desert/sand", category: "travel_scenery" },  // 116
  { name: "desert/vegetation", category: "travel_scenery" },  // 117
  { name: "desert_road", category: "travel_scenery" },  // 118
  { name: "diner/outdoor", category: "foods" },  // 119
  { name: "dining_hall", category: "foods" },  // 120
  { name: "dining_room", category: "foods" },  // 121
  { name: "discotheque", category: "social_activities" },  // 122
  { name: "doorway/outdoor", category: "travel_scenery" },  // 123
  { name: "dorm_room", category: "other" },  // 124
  { name: "downtown", category: "other" },  // 125
  { name: "dressing_room", category: "single_person" },  // 126
  { name: "driveway", category: "other" },  // 127
  { name: "drugstore", category: "other" },  // 128
  { name: "elevator/door", category: "other" },  // 129
  { name: "elevator_lobby", category: "social_activities" },  // 130
  { name: "elevator_shaft", category: "other" },  // 131
  { name: "embassy", category: "travel_scenery" },  // 132
  { name: "engine_room", category: "other" },  // 133
  { name: "entrance_hall", category: "other" },  // 134
  { name: "escalator/indoor", category: "other" },  // 135
  { name: "excavation", category: "other" },  // 136
  { name: "fabric_store", category: "other" },  // 137
  { name: "farm", category: "travel_scenery" },  // 138
  { name: "fastfood_restaurant", category: "foods" },  // 139
  { name: "field/cultivated", category: "travel_scenery" },  // 140
  { name: "field/wild", category: "travel_scenery" },  // 141
  { name: "field_road", category: "travel_scenery" },  // 142
  { name: "fire_escape", category: "travel_scenery" },  // 143
  { name: "fire_station", category: "social_activities" },  // 144
  { name: "fishpond", category: "travel_scenery" },  // 145
  { name: "flea_market/indoor", category: "social_activities" },  // 146
  { name: "florist_shop/indoor", category: "social_activities" },  // 147
  { name: "food_court", category: "foods" },  // 148
  { name: "football_field", category: "travel_scenery" },  // 149
  { name: "forest/broadleaf", category: "travel_scenery" },  // 150
  { name: "forest_path", category: "travel_scenery" },  // 151
  { name: "forest_road", category: "travel_scenery" },  // 152
  { name: "formal_garden", category: "travel_scenery" },  // 153
  { name: "fountain", category: "travel_scenery" },  // 154
  { name: "galley", category: "travel_scenery" },  // 155
  { name: "garage/indoor", category: "travel_scenery" },  // 156
  { name: "garage/outdoor", category: "travel_scenery" },  // 157
  { name: "gas_station", category: "social_activities" },  // 158
  { name: "gazebo/exterior", category: "travel_scenery" },  // 159
  { name: "general_store/indoor", category: "other" },  // 160
  { name: "general_store/outdoor", category: "other" },  // 161
  { name: "gift_shop", category: "social_activities" },  // 162
  { name: "glacier", category: "travel_scenery" },  // 163
  { name: "golf_course", category: "travel_scenery" },  // 164
  { name: "greenhouse/indoor", category: "travel_scenery" },  // 165
  { name: "greenhouse/outdoor", category: "travel_scenery" },  // 166
  { name: "grotto", category: "travel_scenery" },  // 167
  { name: "gymnasium/indoor", category: "social_activities" },  // 168
  { name: "hangar/indoor", category: "travel_scenery" },  // 169
  { name: "hangar/outdoor", category: "travel_scenery" },  // 170
  { name: "harbor", category: "travel_scenery" },  // 171
  { name: "hardware_store", category: "other" },  // 172
  { name: "hayfield", category: "travel_scenery" },  // 173
  { name: "heliport", category: "other" },  // 174
  { name: "highway", category: "travel_scenery" },  // 175
  { name: "home_office", category: "social_activities" },  // 176
  { name: "home_theater", category: "social_activities" },  // 177
  { name: "hospital", category: "social_activities" },  // 178
  { name: "hospital_room", category: "social_activities" },  // 179
  { name: "hot_spring", category: "other" },  // 180
  { name: "hotel/outdoor", category: "other" },  // 181
  { name: "hotel_room", category: "other" },  // 182
  { name: "house", category: "travel_scenery" },  // 183
  { name: "hunting_lodge/outdoor", category: "other" },  // 184
  { name: "ice_cream_parlor", category: "foods" },  // 185
  { name: "ice_floe", category: "other" },  // 186
  { name: "ice_shelf", category: "other" },  // 187
  { name: "ice_skating_rink/indoor", category: "social_activities" },  // 188
  { name: "ice_skating_rink/outdoor", category: "social_activities" },  // 189
  { name: "iceberg", category: "travel_scenery" },  // 190
  { name: "igloo", category: "travel_scenery" },  // 191
  { name: "industrial_area", category: "other" },  // 192
  { name: "inn/outdoor", category: "travel_scenery" },  // 193
  { name: "islet", category: "other" },  // 194
  { name: "jacuzzi/indoor", category: "single_person" },  // 195
  { name: "jail_cell", category: "travel_scenery" },  // 196
  { name: "japanese_garden", category: "travel_scenery" },  // 197
  { name: "jewelry_shop", category: "social_activities" },  // 198
  { name: "junkyard", category: "social_activities" },  // 199
  { name: "kasbah", category: "other" },  // 200
  { name: "kennel/outdoor", category: "pets" },  // 201
  { name: "kindergarden_classroom", category: "social_activities" },  // 202
  { name: "kitchen", category: "foods" },  // 203
  { name: "lagoon", category: "travel_scenery" },  // 204
  { name: "lake/natural", category: "travel_scenery" },  // 205
  { name: "landfill", category: "travel_scenery" },  // 206
  { name: "landing_deck", category: "travel_scenery" },  // 207
  { name: "laundromat", category: "other" },  // 208
  { name: "lawn", category: "travel_scenery" },  // 209
  { name: "lecture_room", category: "social_activities" },  // 210
  { name: "legislative_chamber", category: "other" },  // 211
  { name: "library/indoor", category: "social_activities" },  // 212
  { name: "library/outdoor", category: "social_activities" },  // 213
  { name: "lighthouse", category: "travel_scenery" },  // 214
  { name: "living_room", category: "other" },  // 215
  { name: "loading_dock", category: "travel_scenery" },  // 216
  { name: "lobby", category: "social_activities" },  // 217
  { name: "lock_chamber", category: "travel_scenery" },  // 218
  { name: "locker_room", category: "other" },  // 219
  { name: "mansion", category: "travel_scenery" },  // 220
  { name: "manufactured_home", category: "other" },  // 221
  { name: "market/indoor", category: "social_activities" },  // 222
  { name: "market/outdoor", category: "social_activities" },  // 223
  { name: "marsh", category: "travel_scenery" },  // 224
  { name: "martial_arts_gym", category: "social_activities" },  // 225
  { name: "mausoleum", category: "travel_scenery" },  // 226
  { name: "medina", category: "other" },  // 227
  { name: "mezzanine", category: "other" },  // 228
  { name: "moat/water", category: "other" },  // 229
  { name: "mosque/outdoor", category: "social_activities" },  // 230
  { name: "motel", category: "other" },  // 231
  { name: "mountain", category: "travel_scenery" },  // 232
  { name: "mountain_path", category: "travel_scenery" },  // 233
  { name: "mountain_snowy", category: "travel_scenery" },  // 234
  { name: "movie_theater/indoor", category: "social_activities" },  // 235
  { name: "museum/indoor", category: "social_activities" },  // 236
  { name: "museum/outdoor", category: "social_activities" },  // 237
  { name: "music_studio", category: "social_activities" },  // 238
  { name: "natural_history_museum", category: "social_activities" },  // 239
  { name: "nursery", category: "social_activities" },  // 240
  { name: "nursing_home", category: "other" },  // 241
  { name: "oast_house", category: "travel_scenery" },  // 242
  { name: "ocean", category: "travel_scenery" },  // 243
  { name: "office", category: "social_activities" },  // 244
  { name: "office_building", category: "social_activities" },  // 245
  { name: "office_cubicles", category: "social_activities" },  // 246
  { name: "oilrig", category: "travel_scenery" },  // 247
  { name: "operating_room", category: "other" },  // 248
  { name: "orchard", category: "travel_scenery" },  // 249
  { name: "orchestra_pit", category: "other" },  // 250
  { name: "pagoda", category: "travel_scenery" },  // 251
  { name: "palace", category: "travel_scenery" },  // 252
  { name: "pantry", category: "foods" },  // 253
  { name: "park", category: "social_activities" },  // 254
  { name: "parking_garage/indoor", category: "social_activities" },  // 255
  { name: "parking_garage/outdoor", category: "social_activities" },  // 256
  { name: "parking_lot", category: "social_activities" },  // 257
  { name: "pasture", category: "travel_scenery" },  // 258
  { name: "patio", category: "travel_scenery" },  // 259
  { name: "pavilion", category: "travel_scenery" },  // 260
  { name: "pet_shop", category: "social_activities" },  // 261
  { name: "pharmacy", category: "other" },  // 262
  { name: "phone_booth", category: "travel_scenery" },  // 263
  { name: "physics_laboratory", category: "other" },  // 264
  { name: "picnic_area", category: "other" },  // 265
  { name: "pier", category: "travel_scenery" },  // 266
  { name: "pizzeria", category: "foods" },  // 267
  { name: "playground", category: "social_activities" },  // 268
  { name: "playroom", category: "other" },  // 269
  { name: "plaza", category: "social_activities" },  // 270
  { name: "pond", category: "travel_scenery" },  // 271
  { name: "porch", category: "travel_scenery" },  // 272
  { name: "promenade", category: "travel_scenery" },  // 273
  { name: "pub/indoor", category: "foods" },  // 274
  { name: "racecourse", category: "travel_scenery" },  // 275
  { name: "raceway", category: "travel_scenery" },  // 276
  { name: "raft", category: "other" },  // 277
  { name: "railroad_track", category: "travel_scenery" },  // 278
  { name: "rainforest", category: "travel_scenery" },  // 279
  { name: "reception", category: "other" },  // 280
  { name: "recreation_room", category: "other" },  // 281
  { name: "repair_shop", category: "social_activities" },  // 282
  { name: "residential_neighborhood", category: "travel_scenery" },  // 283
  { name: "restaurant", category: "foods" },  // 284
  { name: "restaurant_kitchen", category: "foods" },  // 285
  { name: "restaurant_patio", category: "foods" },  // 286
  { name: "rice_paddy", category: "other" },  // 287
  { name: "river", category: "travel_scenery" },  // 288
  { name: "rock_arch", category: "travel_scenery" },  // 289
  { name: "roof_garden", category: "travel_scenery" },  // 290
  { name: "rope_bridge", category: "travel_scenery" },  // 291
  { name: "ruin", category: "travel_scenery" },  // 292
  { name: "runway", category: "travel_scenery" },  // 293
  { name: "sandbox", category: "travel_scenery" },  // 294
  { name: "sauna", category: "single_person" },  // 295
  { name: "schoolhouse", category: "social_activities" },  // 296
  { name: "science_museum", category: "social_activities" },  // 297
  { name: "server_room", category: "other" },  // 298
  { name: "shed", category: "travel_scenery" },  // 299
  { name: "shoe_shop", category: "social_activities" },  // 300
  { name: "shopfront", category: "social_activities" },  // 301
  { name: "shopping_mall/indoor", category: "social_activities" },  // 302
  { name: "shower", category: "single_person" },  // 303
  { name: "ski_resort", category: "travel_scenery" },  // 304
  { name: "ski_slope", category: "travel_scenery" },  // 305
  { name: "sky", category: "travel_scenery" },  // 306
  { name: "skyscraper", category: "travel_scenery" },  // 307
  { name: "slum", category: "travel_scenery" },  // 308
  { name: "snowfield", category: "travel_scenery" },  // 309
  { name: "soccer_field", category: "travel_scenery" },  // 310
  { name: "stable", category: "travel_scenery" },  // 311
  { name: "stadium/baseball", category: "social_activities" },  // 312
  { name: "stadium/football", category: "social_activities" },  // 313
  { name: "stadium/soccer", category: "social_activities" },  // 314
  { name: "stage/indoor", category: "social_activities" },  // 315
  { name: "stage/outdoor", category: "social_activities" },  // 316
  { name: "staircase", category: "travel_scenery" },  // 317
  { name: "storage_room", category: "other" },  // 318
  { name: "street", category: "social_activities" },  // 319
  { name: "subway_station/platform", category: "social_activities" },  // 320
  { name: "supermarket", category: "social_activities" },  // 321
  { name: "sushi_bar", category: "foods" },  // 322
  { name: "swamp", category: "travel_scenery" },  // 323
  { name: "swimming_hole", category: "travel_scenery" },  // 324
  { name: "swimming_pool/indoor", category: "social_activities" },  // 325
  { name: "swimming_pool/outdoor", category: "social_activities" },  // 326
  { name: "synagogue/outdoor", category: "social_activities" },  // 327
  { name: "television_room", category: "other" },  // 328
  { name: "television_studio", category: "social_activities" },  // 329
  { name: "temple/asia", category: "social_activities" },  // 330
  { name: "throne_room", category: "travel_scenery" },  // 331
  { name: "ticket_booth", category: "other" },  // 332
  { name: "topiary_garden", category: "travel_scenery" },  // 333
  { name: "tower", category: "social_activities" },  // 334
  { name: "toyshop", category: "social_activities" },  // 335
  { name: "train_interior", category: "travel_scenery" },  // 336
  { name: "train_station/platform", category: "social_activities" },  // 337
  { name: "tree_farm", category: "travel_scenery" },  // 338
  { name: "tree_house", category: "travel_scenery" },  // 339
  { name: "trench", category: "travel_scenery" },  // 340
  { name: "tundra", category: "travel_scenery" },  // 341
  { name: "underwater/ocean_deep", category: "travel_scenery" },  // 342
  { name: "utility_room", category: "other" },  // 343
  { name: "valley", category: "travel_scenery" },  // 344
  { name: "vegetable_garden", category: "travel_scenery" },  // 345
  { name: "veterinarians_office", category: "social_activities" },  // 346
  { name: "viaduct", category: "travel_scenery" },  // 347
  { name: "village", category: "travel_scenery" },  // 348
  { name: "vineyard", category: "social_activities" },  // 349
  { name: "volcano", category: "travel_scenery" },  // 350
  { name: "volleyball_court/outdoor", category: "social_activities" },  // 351
  { name: "waiting_room", category: "other" },  // 352
  { name: "water_park", category: "social_activities" },  // 353
  { name: "water_tower", category: "social_activities" },  // 354
  { name: "waterfall", category: "travel_scenery" },  // 355
  { name: "watering_hole", category: "travel_scenery" },  // 356
  { name: "wave", category: "travel_scenery" },  // 357
  { name: "wet_bar", category: "foods" },  // 358
  { name: "wheat_field", category: "travel_scenery" },  // 359
  { name: "wind_farm", category: "travel_scenery" },  // 360
  { name: "windmill", category: "travel_scenery" },  // 361
  { name: "yard", category: "social_activities" },  // 362
  { name: "youth_hostel", category: "travel_scenery" },  // 363
  { name: "zen_garden", category: "travel_scenery" },  // 364
];

export default PLACES365_CLASSES;
